"""Initial tables

Revision ID: 61cbf82613da
Revises: 
Create Date: 2026-04-04 12:47:44.276982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cbf82613da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wild_encounters_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=17), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wild_encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pokemon', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=17), nullable=False),
    sa.ForeignKeyConstraint(['id_pokemon'], ['pokemons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wild_encounters')
    op.drop_table('wild_encounters_level')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
